"""Nextt Migration

Revision ID: 6c4d49128cde
Revises: f694c80abf6f
Create Date: 2023-05-13 14:26:34.614967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c4d49128cde'
down_revision = 'f694c80abf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('customerimages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customerimages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
