"""Nextttt Migration

Revision ID: 9479f19faae4
Revises: 6c4d49128cde
Create Date: 2023-05-15 00:00:42.078255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9479f19faae4'
down_revision = '6c4d49128cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customerimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))

    with op.batch_alter_table('worktime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worktime', schema=None) as batch_op:
        batch_op.drop_column('createat')

    with op.batch_alter_table('customerimages', schema=None) as batch_op:
        batch_op.drop_column('updateat')
        batch_op.drop_column('createat')

    # ### end Alembic commands ###
