"""Nexttttt Migration

Revision ID: 9fe215a4f74d
Revises: 9479f19faae4
Create Date: 2023-05-15 11:32:22.918422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fe215a4f74d'
down_revision = '9479f19faae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingdate', sa.Date(), nullable=True))
        batch_op.alter_column('bookingtime',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('bookingtime',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('bookingdate')

    # ### end Alembic commands ###
