"""Second migration

Revision ID: cf99095c9059
Revises: bf869c7b5377
Create Date: 2023-05-10 10:17:17.807423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf99095c9059'
down_revision = 'bf869c7b5377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hide', sa.Boolean(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hide', sa.Boolean(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hide', sa.Boolean(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hide', sa.Boolean(), nullable=True))

    with op.batch_alter_table('worktime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updateat', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worktime', schema=None) as batch_op:
        batch_op.drop_column('updateat')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('hide')
        batch_op.drop_column('updateat')
        batch_op.drop_column('createat')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('hide')
        batch_op.drop_column('updateat')
        batch_op.drop_column('createat')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('hide')
        batch_op.drop_column('updateat')
        batch_op.drop_column('createat')

    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('hide')
        batch_op.drop_column('updateat')
        batch_op.drop_column('createat')

    # ### end Alembic commands ###
